"""Add is_admin to User model

Revision ID: 15defee7e7f2
Revises: 40a83b449a8d
Create Date: 2025-02-20 12:43:13.639373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15defee7e7f2'
down_revision = '40a83b449a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
