"""empty message

Revision ID: 214cdcc8cd1f
Revises: a494fb5ca04d
Create Date: 2025-02-21 06:43:10.396915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214cdcc8cd1f'
down_revision = 'a494fb5ca04d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('nationality')

    # ### end Alembic commands ###
